- name: Configure nginx loadbalancer
  template: src="loadbalancer.j2" dest="/etc/nginx/sites-enabled/loadbalancer"
  notify: restart nginx
  tags: configuration

- name: Remove default configuration
  file: path="/etc/nginx/sites-enabled/default" state=absent
  notify: restart nginx
  tags: configuration